#!/usr/bin/env python3
"""
Regenerate catalog.json from the image files committed in this repo.

  clubs/<slug>-club-square.jpg             -> clubs[slug].square        (immersive crowd)
  clubs-drummer/<slug>-drummer-square.jpg  -> clubs[slug].square_drummer (drummer/capo)
  matchups/<key>-square.jpg                -> matchups[key].square
  matchups/<key>-landscape.jpg             -> matchups[key].landscape

Then alias keys are added (copying the canonical entry) so the catalog matches
the feed enricher's deployed slug convention (it emits ac-milan / inter-milan).

Run after adding/removing any images:  python3 build-catalog.py
"""

import json
import glob
import os
import re

ROOT = os.path.dirname(os.path.abspath(__file__))
BASE = "https://raw.githubusercontent.com/Markvdeng/lft-image-catalog/main"

# alias slug (as emitted by the deployed enricher) -> canonical slug we host under
CLUB_ALIASES = {"ac-milan": "milan", "inter-milan": "inter"}
MATCHUP_ALIASES = {"ac-milan-vs-inter-milan": "milan-vs-inter"}

clubs: dict = {}
for f in glob.glob(f"{ROOT}/clubs/*-club-square.jpg"):
    slug = os.path.basename(f)[: -len("-club-square.jpg")]
    clubs.setdefault(slug, {})["square"] = f"{BASE}/clubs/{os.path.basename(f)}"
for f in glob.glob(f"{ROOT}/clubs-drummer/*-drummer-square.jpg"):
    slug = os.path.basename(f)[: -len("-drummer-square.jpg")]
    clubs.setdefault(slug, {})["square_drummer"] = f"{BASE}/clubs-drummer/{os.path.basename(f)}"

matchups: dict = {}
for f in glob.glob(f"{ROOT}/matchups/*.jpg"):
    b = os.path.basename(f)
    m = re.match(r"^(.*)-(square|landscape)\.jpg$", b)
    if not m:
        continue
    matchups.setdefault(m.group(1), {})[m.group(2)] = f"{BASE}/matchups/{b}"

for alias, canon in CLUB_ALIASES.items():
    if canon in clubs:
        clubs[alias] = dict(clubs[canon])
for alias, canon in MATCHUP_ALIASES.items():
    if canon in matchups:
        matchups[alias] = dict(matchups[canon])

catalog = {
    "_comment": "LFT image catalog for Google Ads dynamic image assets. Consumed by feed-enricher-pro. 'clubs' keyed by the enricher's *_slug_final (square=immersive crowd, square_drummer=drummer/capo, both 1:1 1200x1200); 'matchups' keyed by '<home_slug>-vs-<away_slug>' (square 1:1 + landscape 1.91:1, drummer-VS style). Alias keys mirror the deployed ac-milan/inter-milan slugs. Generated by build-catalog.py — do not hand-edit.",
    "clubs": {k: clubs[k] for k in sorted(clubs)},
    "matchups": {k: matchups[k] for k in sorted(matchups)},
}

with open(f"{ROOT}/catalog.json", "w") as fh:
    fh.write(json.dumps(catalog, indent=2) + "\n")

print(f"catalog.json: {len(clubs)} club keys ({sum('square_drummer' in v for v in clubs.values())} with drummer), {len(matchups)} matchup keys")
